### ISSUE TITLE
Panic error

### ISSUE THREAD

**Issue by WillPPK** [Martini-Force-Field-Initiative/Bartender#6]
I think the QM simulations are not running for some reasons? Any idea?

```
 bartender pbc.pdb 1PBC_bartender.inp -charge 0 -v 

Use:
  $BARTENDERPATH/bartender  [FLAGS] geometry_file input_file
 Use "bartender -help" to see the available flags

panic: Failed produce a readable XTB QM-MD trajectory open xtb.trj: no such file or directory

goroutine 1 [running]:
main.MD(0xc000096510, {0x7676e8, 0xc000014780}, 0x7?)
	/wrk/programs/github.com/rmera/bartender-dev_noBeads/qm.go:205 +0x2a5
main.main()
	/wrk/programs/github.com/rmera/bartender-dev_noBeads/main.go:232 +0x1410

```

Cheers

**Comment by GilbertoPPereira** [comment]
Hey.

For you to run a QM simulation, you need to set the following flag: -method gfn2, otherwise you will run a GFNFF implicit solvent MD simulation. About your error: It may be the case that the pdb file is not being well-read by BT. 
Could you share the file?

Best,
Gil

**Comment by rmera** [comment]
Hey,

The flags need to go before the required data (input files).
That could be causing the problem.

Otherwise, it seems that there was an error running xtb. If xtb ran at all, there should be a file called gochem.out in your directory (the xtb output). Could you please share the last, say, 20 lines in that file?  The 

I'll be adding something about this to the Wiki.

**Comment by WillPPK** [comment]
Yup - checked the gochem.out.

xtb not found. So probably something with the installation..

**Comment by WillPPK** [comment]
Ok - now it is working.  The case is fixed!
